### PR TITLE
[#160970775] create the landing page

### PR DESCRIPTION
**Pull request by charitymarani**
#### What does this PR do?
 This PR creates a landing page where users can search for questions, view latest and top questions and have an option to post a question
#### Description of Task to be completed?
1.created PT story for the landing page
2.wrote HTML code for landing page
3.wrote CSS code for landing page
#### How should this be manually tested?
clone this repo git clone https://github.com/KelynPNjeri/StackOverflow_lite-Phoenix
cd into StackOverflow_lite-Phoenix
checkout to ft-landing-page branch: git checkout ft-landing-page
open index.html in a browser
#### What are the relevant pivotal tracker stories?
#160970775
#### Screenshots (if appropriate)
screenshot 229

#### Questions:
What do you think about the design

### CODE REVIEW

**Comment by wandesky** [comment]
The design is elegant. It delivers on what we agreed as a group. 
Good work @charitymarani

**Comment by charitymarani** [comment]
what did we agree about the colors btw? @wandesky @JamesnThuo @DennisMufasa @KelynPNjeri 
Thanks @wandesky

**Comment by wandesky** [comment]
The theme colour is blue. For the homepage, I remember we agreed to have some blue with white dominating the page. The header and the footer remain blue while the body of the homepage is white(or a shade of white).

**Comment by Makavura** [comment]
https://www.color-hex.com/color/3b5998
color code

**Pull request merged**
